import { Link } from 'react-router-dom';
import Button from 'react-bootstrap/Button';
import Col from 'react-bootstrap/Col';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Icon from '../components/Icon';
import { useShop } from '../context/ShopContext';

export default function CarePage(){const {studioSettings}=useShop();const ready=studioSettings?.leadTimes?.ready||'3–10 business days';const custom=studioSettings?.leadTimes?.custom||'5–15 business days';return <><section className="page-hero care-hero"><Container fluid="xl"><p className="eyebrow">Care & delivery</p><h1>Made to last.<br/><em>Packed to travel.</em></h1><p>A little care keeps your resin piece luminous, smooth and beautiful for years.</p></Container></section><section className="page-section care-guide"><Container fluid="xl"><Row className="g-4">{[['spark','Soft cloth only','Clean gently with a dry or slightly damp microfiber cloth.'],['shield','Avoid harsh chemicals','Household cleaners and abrasives may dull or mark the finish.'],['spark','Limit direct sun','Avoid prolonged strong sunlight to protect colours and clarity.'],['package','Handle thoughtfully','Prevent drops, deep scratches and contact with very hot surfaces.']].map(([icon,title,text])=><Col sm={6} lg={3} key={title}><article><span><Icon name={icon}/></span><h2>{title}</h2><p>{text}</p></article></Col>)}</Row></Container></section><section className="delivery-timeline"><Container fluid="xl"><Row className="gy-5"><Col lg={5}><p className="eyebrow light-eyebrow">From studio to doorstep</p><h2>Good work takes the time it needs.</h2><p>Each estimate starts after design details are confirmed. Complex or bulk pieces may need a separately agreed schedule.</p></Col><Col lg={{span:6,offset:1}}><div className="timeline-list"><div><span>01</span><p><strong>Ready & small-batch pieces</strong><small>Usually processed in {ready}.</small></p></div><div><span>02</span><p><strong>Custom orders</strong><small>Usually processed in {custom} after concept approval.</small></p></div><div><span>03</span><p><strong>Quality & packaging</strong><small>Multiple checks, premium gift wrap, protective bubble wrap and a secure corrugated box.</small></p></div><div><span>04</span><p><strong>PAN India delivery</strong><small>Transit timing and any delivery charge are confirmed for your address.</small></p></div></div></Col></Row></Container></section><section className="page-section packaging-section"><Container fluid="xl"><header className="centered-heading section-heading"><p className="eyebrow">Inside every order</p><h2>Presentation, protected.</h2></header><div className="packaging-list">{['Premium gift packaging','Protective bubble wrap','Secure corrugated box','Care instructions','Thank-you card'].map(item=><span key={item}><Icon name="check"/>{item}</span>)}</div><div className="section-cta"><Button as={Link} to="/shop" className="button-burgundy">Choose a piece <Icon name="arrow"/></Button></div></Container></section></>}
